version: "3.8"
services:
  # db:
  #   image: postgres:14.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  # api:
  #   image: node:slim
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"
  #   command: "npm run start"

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    # volumes:
    #   - persistent:/var/lib/mysql
  myapp:
    build: .
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_HOST=db
    depends_on:
      - db
